### ISSUE TITLE
Things that need to be done.

### ISSUE THREAD

**Issue by DreamSleeper64** [KiwisVersusKoalas/BonteKoe#3]
## Current situation
**List of activities**

Before Realisation:
- [x] Informatie Rapportbehoefte
- [x] Functioneel Ontwerp
- [x] Technisch Ontwerp
- [x] Logo CodeIT
- [x] Huisstijl CodeIT
- [x] Logo BonteKoe
- [x] Lay-out BonteKoe

While Realisation:
- [x] Landingpage

- [x] Restaurant Informatiepagina
- [x] Restaurant Menupagina
- [x] Restaurant Menu back end
- [x] Restaurant Menu front end (Menukaart + --- functionele tabs)
- [x] Restaurant Reserveringspagina
- [x] Restaurant Reservering backend

- [x] Discozalen Informatiepagina

Files
- [x] Index.php  (  Landingpage  )

- [x] Discomain.php  (  Infopagina Discozalen  )
- [x] Zalen.php  
- [x] Evenementen.php
- [x] Disco_contact.php
- [x] Restaurantmain.php (missing Frontend!)
- [x] Reservering.php (missing Frontend!)
- [x] Menu.php
- [x] About.php
- [x] Contact.php
- [x] Config.php
- [x] Styles.css
- [x] All images

After Realisation:

- [x] "big bang" testing by developers
- [x] "big bang" testing by users
- [x] Final Documentation
- [x] Creating a PowerPoint Presentation
- [x] We all get a superb grade!

**Comment by Vincent030299** [comment]
toppie

**Comment by Cp-022** [comment]
wat bemoie jij je dr mee
