### ISSUE TITLE
Betreft Intensieve week

### ISSUE THREAD

**Issue by DreamSleeper64** [KiwisVersusKoalas/BonteKoe#4]
Beste teamgenoten van KiwisVersusKoalassus BonteKoe,

De intensieve week is voorbij, ik hoop dat wij allen er veel van hebben geleerd, ik in ieder geval wel.
Deze week zijn wij allen geheel bezig geweest met iets anders, dit betekent dat het moeilijker wordt om terug op het juiste spoor te komen en vooral nu we nog maar 2 a 3 weken hebben voordat het moet worden ingeleverd. 

Toch ben ik er zeker van dat dit ons nog gaat lukken, we zijn in principe klaar, it all depends on our friendly front-end developers om er een mooie afsluiting van te maken. 

Succes jongens, tot ALA

**Comment by Cp-022** [comment]
pfff ez, was wel lache imo (je hebt KiwisVersusKoalas verkeerd geschreven 
>KiwisVersusKoalassus )
:P

**Comment by DreamSleeper64** [comment]
Nee Nee, Het is net als Pipo's project, ik plaatste er een s achter zo van, de Bonte Koe van Kiwis Vs Koalas.  KiwisVsKoalas's ( klinkt raar dus ik deed sus )

**Comment by Cp-022** [comment]
Seems legit
